import os
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_openai import ChatOpenAI

class SummarizationModule:
    def __init__(self, model_name: str = "gpt-4o", temperature: float = 0.5):
        """
        Initializes the SummarizationModule with an LLM and prompt templates.
        Args:
            model_name: The name of the OpenAI model to use.
            temperature: The sampling temperature for the LLM (lower for more factual/less creative).
        """
        self.llm = None
        self.model_name = model_name
        self.temperature = temperature
        self.output_parser = StrOutputParser()

        self.summary_prompt_template = ChatPromptTemplate.from_messages(
            [
                ("system", "You are an expert summarizer. Your goal is to condense complex information into clear, concise, and accurate summaries."),
                ("user", "Summarize the following text:\n\n{text}\n\nSummary:")
            ]
        )

        self.brief_summary_prompt_template = ChatPromptTemplate.from_messages(
            [
                ("system", "You are an expert summarizer. Your goal is to condense complex information into very brief, clear, and accurate summaries, focusing only on the most critical points."),
                ("user", "Provide a brief summary of the following text:\n\n{text}\n\nBrief Summary:")
            ]
        )

    def generate_summary(self, text: str, detail_level: str = "normal") -> str:
        """
        Generates a summary of the provided text using an LLM.
        Args:
            text: The input text to summarize.
            detail_level: The desired detail level for the summary ('normal' or 'brief').
        Returns:
            A concise summary generated by the LLM.
        """
        if "OPENAI_API_KEY" not in os.environ:
            raise ValueError("OPENAI_API_KEY environment variable is not set.")

        if self.llm is None:
            self.llm = ChatOpenAI(model_name=self.model_name, temperature=self.temperature)

        if detail_level == "brief":
            prompt = self.brief_summary_prompt_template
        else:
            prompt = self.summary_prompt_template

        chain = prompt | self.llm | self.output_parser
        return chain.invoke({"text": text})

if __name__ == "__main__":
    # Example usage (requires OPENAI_API_KEY environment variable to be set)
    if "OPENAI_API_KEY" not in os.environ:
        print("Please set the OPENAI_API_KEY environment variable.")
    else:
        summarizer = SummarizationModule()
        sample_text = """
        The Roman Empire was a vast and powerful civilization that ruled much of Europe and North Africa for over 1000 years.
        It was founded in 27 BC when Octavian became the first Roman Emperor, Augustus. The Empire was characterized by its
        strong military, advanced engineering, and sophisticated legal system. Its capital, Rome, was a thriving metropolis
        with impressive architecture, including the Colosseum and the Pantheon. The Pax Romana, a period of relative peace
        and stability, allowed the Empire to flourish and expand its influence. However, internal strife, economic problems,
        and external pressures from barbarian tribes eventually led to the decline and fall of the Western Roman Empire in 476 AD.
        The Eastern Roman Empire, also known as the Byzantine Empire, continued for another thousand years.
        """
        print("--- Normal Summary ---")
        normal_summary = summarizer.generate_summary(sample_text)
        print(normal_summary)

        print("\n--- Brief Summary ---")
        brief_summary = summarizer.generate_summary(sample_text, detail_level="brief")
        print(brief_summary)
